apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-service-config
data:
  MONGO_URI: "mongodb://mongodb-service:27017"
  MONGO_DB: "ai_chatbot"
  COLLECTION_NAME: "product_collection"
  DB_CHAT_HISTORY_COLLECTION: "chat_history"
  semanticCacheCollection: "semantic_cache"
  VECTOR_STORE: "/app/databaseQQ/VECTOR_STORE"
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-service-secrets
type: Opaque
data:
  # Base64 encoded Gemini API key - replace with your actual key
  GENMINI_API_KEY: "REPLACE_WITH_YOUR_BASE64_ENCODED_API_KEY"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  labels:
    app: ai-service
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: http
  selector:
    app: ai-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  labels:
    app: ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: ai-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: ai-service-config
          env:
            - name: GENMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-service-secrets
                  key: GENMINI_API_KEY
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: vector-store
              mountPath: /app/databaseQQ/VECTOR_STORE
      volumes:
        - name: vector-store
          emptyDir: {}
