apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
        configuration:
          brokers:
            - broker: 0
              advertisedHost: my-cluster-kafka-bootstrap.kafka.svc.cluster.local
              advertisedPort: 9092
    storage:
      type: persistent-claim
      size: 10Gi
    config:
      message.max.bytes: 209715200 # 200MB
      replica.fetch.max.bytes: 209715200
      auto.create.topics.enable: false

  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 5Gi
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1

  entityOperator:
    topicOperator: {}
    userOperator: {}
